name: Java CI with Maven and JUnit

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 18

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests with JUnit
      run: mvn test --file pom.xml